services:
  web:
    image: odoo:19.0
    depends_on:
      - db
    restart: always
    
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - ODOO_MASTER_PASS=admin

    volumes:
      - odoo-web-data:/var/lib/odoo
      - ../files/config:/etc/odoo
      - ../files/addons:/mnt/extra-addons

    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.odoo.rule=Host(`odoo.open-mercato.pl`)
      - traefik.http.routers.odoo.entrypoints=websecure
      - traefik.http.routers.odoo.tls.certresolver=letsencrypt
      - traefik.http.services.odoo.loadbalancer.server.port=8069

  db:
    image: postgres:17
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    restart: always
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    networks:
      - dokploy-network

volumes:
  odoo-web-data:
  odoo-db-data:

networks:
  dokploy-network:
    external: true